### ISSUE TITLE
Gemfile.lock missing from repo

### ISSUE THREAD

**Issue by pablocrivella** [Oldharlem/hsm_assignment#1]
Could you include the Gemfile.lock?

I'm having issues installing the mysql gem since I dind't have mysql db installed, but even after installing it the gem fails to build.
Then I tried to use the Docker container to run the app but the `Gemfile.lock` is missing.

**Comment by Oldharlem** [comment]
Hi @pablocrivella 

The lock file wasn't added to gitignore but refused to add itself to the repo.
The latest commit 8b8dafb4d135ef1ca76eb395279e3cbb42e75571 adds the lock file and you should be able to run either the `docker-compose up` command or `RACK_ENV=local thin start`
